### ISSUE TITLE
Add notice-error class to 2FA notice

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#3]
I couldn't find it in the repo code, but I do see it on the demo website. We should add either `notice-error` or `notice-warning` to the 2FA notice, so it stands out more. I would go with error/red because it is a required step, and for this reason, I would also remove `is-dismissable`. 

![image](https://user-images.githubusercontent.com/1692600/180305761-13a206e0-fb74-4a95-8e7c-2d700e41eb5a.png)

**Comment by KTS915** [comment]
The code is in `registration-users.php` in `mu-plugins`.

It's not an error, so it shouldn't be `notice-error`, and `notice-warning` actually makes it show up less than the current `notice`, so I don't agree with either of these suggestions. I'm also not sure how anyone could miss it as it is, because it's quite large as the font size is set to 150%.
![Screenshot from 2022-07-21 16-43-08](https://user-images.githubusercontent.com/4127662/180311829-251a903e-b449-4d04-a634-3ea277e26cee.png)

I'll never agree with removing `is-dismissible` either. That's just bad manners. The notice comes back when the page is refreshed anyway, but if someone wants to get rid of it temporarily for some reason (e.g. to have more screen real estate) then they should be able to do so.

**Comment by viktorix** [comment]
Then `notice-info` should be the right option.

**Comment by KTS915** [comment]
Now done via commit referenced above.
