### ISSUE TITLE
Alphabetical sorting doesn't work on developers page

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#7]
Clicking on letters that should have a developer listed doesn't show anything:
https://test-directory.webby-books.com/developers/

**Comment by KTS915** [comment]
It's working perfectly for me. I think the issue here is that it currently sorts individuals by last name, whereas some of those who have signed up are using something for their display name that doesn't include their last name. So I think the remedy is instead to sort by first letter of display name.

**Comment by KTS915** [comment]
Addressed by above commit.

**Comment by viktorix** [comment]
Works.
